language: php

php:
  - "5.4"
  - "5.3"

before_install:
  - cd ../../
  - git clone git://github.com/laravel/laravel.git
  - mv ./codenitive/laravel-oneauth ./laravel/bundles/oneauth
  - echo "<?php return array('oneauth' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "phpunit --coverage-text --configuration bundles/oneauth/phpunit.xml"